# Generated by Django 3.2.6 on 2021-09-18 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1500)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('venue', models.CharField(default='', max_length=5000)),
                ('eventdate', models.DateField()),
                ('time', models.TimeField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['-eventdate', 'time'],
            },
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='gallery')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
