# Generated by Django 3.2.6 on 2021-09-18 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_events_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='cause',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='cause',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
