# Generated by Django 3.2.6 on 2021-09-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20210918_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='images',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='venue',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
