# Generated by Django 3.2.6 on 2021-09-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20210918_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='images',
        ),
    ]
